CREATE DATABASE IF NOT EXISTS excel_viewer_db;
USE excel_viewer_db;

CREATE TABLE IF NOT EXISTS users (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email    VARCHAR(150) NOT NULL,
    password VARCHAR(60)  NOT NULL
);

ALTER TABLE users
    MODIFY password VARCHAR(60) NOT NULL;
